waypoints:
  - position:
      x: 0.0
      y: 3.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

  - position:
      x: 6.0
      y: 4.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.2588
      w: 0.9659

  - position:
      x: 6.5
      y: -1.4
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 1.0
      w: 0.0

  - position:
      x: -1.6
      y: -2.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.6088
      w: 0.7934

