waypoints:
  - position:
      x: -0.7
      y: -0.58
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

  - position:
      x: 2.1
      y: -3.1
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.1

  - position:
      x: 4.4
      y: -1.8
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

  - position:
      x: 3.6
      y: 5.6
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.1

